#!/usr/bin/env ruby
#^syntax detection

site "https://galaxy.ansible.com/api/v1"

role "ansible-docker",
  github: "mhamrah/ansible-docker"
role "ansible-java8",
  github: "mhamrah/ansible-java8"
role "ansible-zookeeper",
  github: "mhamrah/ansible-zookeeper"
role "ansible-marathon",
  github: "mhamrah/ansible-marathon"
role "ansible-mesos",
  github: "mhamrah/ansible-mesos"
role "ansible-consul",
  github: "mhamrah/ansible-consul"
