---
- hosts: [all]
  sudo: True
  tags: ['system']
  pre_tasks:
    - name: Install Debian Packages
      apt: pkg={{ item }} state=present update_cache=yes
      with_items:
        - git
        - vim
        - htop
        - unzip
      when: ansible_os_family == "Debian"
    - name: Downloading and enable the EPEL repository definitions.
      yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present
      when: ansible_os_family == "RedHat"
    - name: Install Redhat Packages 
      yum: pkg={{ item }} state=present
      with_items:
        - java7
        - git
        - vim
        - htop
        - unzip
      when: ansible_os_family == "RedHat"
    - name: Disable iptables
      action: service name=iptables state=stopped enabled=false
      when: ansible_os_family == "RedHat"
    - name: Remove require tty
      lineinfile: regexp="^\s+\w+\s+requiretty" dest=/etc/sudoers state=absent
    - name: Remove require tty - alt
      lineinfile: regexp="requiretty" dest=/etc/sudoers.d/os_defaults state=absent
  
